import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/share/Navbar";
import QueryProvider from "./providers/QueryProvider";
import Footer from "./components/share/Footer";
import { ProductProvider } from "./context/ProductContext";
import { Toaster } from "react-hot-toast";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en"  className="h-full">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ProductProvider>
          <QueryProvider>
            <Toaster position="top-right" />
          <Navbar/>
        <main className="min-h-[60vh]">
          {children}
        </main>
        <Footer/>
        </QueryProvider>
        </ProductProvider>
      </body>
    </html>
  );
}
